# Generated by Django 4.1 on 2022-08-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(blank=True, default='noImg.png', null=True, upload_to=''),
        ),
    ]
