# Generated by Django 4.1 on 2022-08-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_photo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/media/noImg.png', null=True, upload_to=''),
        ),
    ]
