# Generated by Django 4.1 on 2022-08-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
