# Generated by Django 4.1 on 2022-09-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_alter_photo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(blank=True, default='noImg.png', null=True, upload_to='images/'),
        ),
    ]
